apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-base
  namespace: thanos
  labels:
    app: thanos-receive-controller
data:
  hashrings.json: |
    [
        {
            "hashring": "staging",
            "tenants": ["test1", "test2", "test3"]
        },
        {
            "hashring": "default",
            "tenants": []
        }
    ]
---