#create namespace avalanche
apiVersion: v1
kind: Namespace
metadata:
  name: avalanche
---
#create deployment avalanche
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-test1
  namespace: avalanche
  labels:
    name: avalanche-test1
spec:
  selector:
    matchLabels:
      app: avalanche-test1
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: avalanche-test1
    spec:
      containers:
        - name: pg-avalanche
          image: jmichalek/avalanche:190b1b7f68cfa7b776137ef4fc803c39a3b14edf
          args:
            - "--metric-count=100"
            - "--series-count=50"
            - "--port=9001"
            - "--remote-url=http://thanos-receive-default.thanos.svc:19291/api/v1/receive"
            - "--remote-requests-count=1000000"
            - "--remote-tenant=test1"
            - "--const-label=env=test1"
            - "--remote-tenant-header-name=THANOS-TENANT"
          ports:
            - containerPort: 9001
---
#create deployment avalanche
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-test2
  namespace: avalanche
  labels:
    name: avalanche-test2
spec:
  selector:
    matchLabels:
      app: avalanche-test2
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: avalanche-test2
    spec:
      containers:
        - name: pg-avalanche
          image: jmichalek/avalanche:190b1b7f68cfa7b776137ef4fc803c39a3b14edf
          args:
            - "--metric-count=100"
            - "--series-count=50"
            - "--port=9001"
            - "--remote-url=http://thanos-receive-default.thanos.svc:19291/api/v1/receive"
            - "--remote-requests-count=1000000"
            - "--remote-tenant=test2"
            - "--const-label=env=test2"
            - "--remote-tenant-header-name=THANOS-TENANT"
          ports:
            - containerPort: 9001
---
#create deployment avalanche
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-test3
  namespace: avalanche
  labels:
    name: avalanche-test3
spec:
  selector:
    matchLabels:
      app: avalanche-test3
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: avalanche-test3
    spec:
      containers:
        - name: pg-avalanche
          image: jmichalek/avalanche:190b1b7f68cfa7b776137ef4fc803c39a3b14edf
          args:
            - "--metric-count=100"
            - "--series-count=50"
            - "--port=9001"
            - "--remote-url=http://thanos-receive-default.thanos.svc:19291/api/v1/receive"
            - "--remote-requests-count=1000000"
            - "--remote-tenant=test3"
            - "--const-label=env=test3"
            - "--remote-tenant-header-name=THANOS-TENANT"
          ports:
            - containerPort: 9001