resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - files:
      - config.yaml
    name: prometheus
    namespace: monitoring